#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_ENV_FILE="$SCRIPT_DIR/test-advanced-znuny-agentlist-all.env"

CONFIG_VARS=(
    ZNUNY_BASE_URL
    ZNUNY_API_USER
    ZNUNY_API_PASS
    EXPECTED_VERSION
    MIN_EXPECTED_VERSION
    TEST_TICKET_ID
    TEST_TICKET_NUMBER
    TEST_QUEUE_ID
    TEST_QUEUE_DISPLAY_NAME
    TEST_QUEUE_NAME_PATH
    TEST_PRIORITY_NAME
    TEST_CUSTOMER_SEARCH
    TEST_CUSTOMER_LOGIN
    TEST_HOSTNAME
    RUN_WRITE_TESTS
    LOG_DIR
)

PASS=0
WARN=0
FAIL=0
SKIP=0
LOG_FILE=""

env_is_set() {
    env | grep -q "^$1="
}

capture_exported_overrides() {
    local var
    for var in "${CONFIG_VARS[@]}"; do
        if env_is_set "$var"; then
            printf -v "__ENV_SET_$var" '%s' 1
            printf -v "__ENV_VALUE_$var" '%s' "${!var-}"
        else
            printf -v "__ENV_SET_$var" '%s' 0
            printf -v "__ENV_VALUE_$var" '%s' ""
        fi
    done
}

restore_exported_overrides() {
    local var is_set value is_set_var value_var
    for var in "${CONFIG_VARS[@]}"; do
        is_set_var="__ENV_SET_$var"
        value_var="__ENV_VALUE_$var"
        is_set=${!is_set_var:-0}
        if [ "$is_set" = "1" ]; then
            value=${!value_var}
            printf -v "$var" '%s' "$value"
        fi
    done
}

load_env_file() {
    capture_exported_overrides
    if [ -f "$TEST_ENV_FILE" ]; then
        # shellcheck disable=SC1090
        . "$TEST_ENV_FILE"
    fi
    restore_exported_overrides
}

trim_slash() {
    local value=${1:-}
    value=${value%/}
    printf '%s' "$value"
}

mask_text() {
    local text=${1-}
    if [ -n "${ZNUNY_API_PASS:-}" ]; then
        local encoded_pass
        encoded_pass=$(urlencode "$ZNUNY_API_PASS" 2>/dev/null || printf '')
        text=${text//${ZNUNY_API_PASS}/[hidden]}
        if [ -n "$encoded_pass" ]; then
            text=${text//${encoded_pass}/[hidden]}
        fi
    fi
    printf '%s' "$text"
}

log_line() {
    local message
    message=$(mask_text "$*")
    printf '%s\n' "$message"
    if [ -n "$LOG_FILE" ]; then
        printf '%s\n' "$message" >>"$LOG_FILE"
    fi
}

section() {
    log_line ""
    log_line "== $* =="
}

pass() {
    PASS=$((PASS + 1))
    log_line "PASS: $*"
}

warn() {
    WARN=$((WARN + 1))
    log_line "WARN: $*"
}

fail() {
    FAIL=$((FAIL + 1))
    log_line "FAIL: $*"
}

skip() {
    SKIP=$((SKIP + 1))
    log_line "SKIP: $*"
}

prompt_required() {
    local var=$1
    local label=$2
    local value

    value=${!var:-}
    while [ -z "$value" ]; do
        printf '%s: ' "$label"
        IFS= read -r value
        if [ -z "$value" ]; then
            printf 'Value is required.\n'
        fi
    done
    printf -v "$var" '%s' "$value"
}

prompt_optional() {
    local var=$1
    local label=$2
    local value

    value=${!var:-}
    if [ -z "$value" ]; then
        printf '%s: ' "$label"
        IFS= read -r value
        printf -v "$var" '%s' "$value"
    fi
}

prompt_yes_no_default_no() {
    local var=$1
    local label=$2
    local value

    value=${!var:-}
    if [ -z "$value" ]; then
        printf '%s [y/N]: ' "$label"
        IFS= read -r value
        case "$value" in
            y|Y|yes|YES|Yes) value=yes ;;
            *) value=no ;;
        esac
        printf -v "$var" '%s' "$value"
    fi
}

prompt_password_if_needed() {
    if [ -n "${ZNUNY_API_PASS:-}" ]; then
        return
    fi

    printf 'API password: '
    stty -echo 2>/dev/null || true
    IFS= read -r ZNUNY_API_PASS
    stty echo 2>/dev/null || true
    printf '\n'

    while [ -z "$ZNUNY_API_PASS" ]; do
        printf 'API password is required: '
        stty -echo 2>/dev/null || true
        IFS= read -r ZNUNY_API_PASS
        stty echo 2>/dev/null || true
        printf '\n'
    done
}

shell_quote() {
    local value=${1-}
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

urlencode_spaces_only() {
    local value=${1-}
    printf '%s' "${value// /%20}"
}

write_env_file() {
    local store_password=$1
    {
        printf '# Generated by scripts/test-advanced-znuny-agentlist-all.sh\n'
        printf '# Do not commit real secrets.\n'
        if [ "$store_password" = "yes" ]; then
            printf '# WARNING: this file contains a secret.\n'
        fi
        printf '\n'
        printf 'ZNUNY_BASE_URL=%s\n' "$(shell_quote "$ZNUNY_BASE_URL")"
        printf 'ZNUNY_API_USER=%s\n' "$(shell_quote "$ZNUNY_API_USER")"
        if [ "$store_password" = "yes" ]; then
            printf 'ZNUNY_API_PASS=%s\n' "$(shell_quote "$ZNUNY_API_PASS")"
        else
            printf '# ZNUNY_API_PASS=\n'
        fi
        printf '\n'
        printf 'EXPECTED_VERSION=%s\n' "$(shell_quote "${EXPECTED_VERSION:-}")"
        printf 'MIN_EXPECTED_VERSION=%s\n' "$(shell_quote "$MIN_EXPECTED_VERSION")"
        printf '\n'
        printf 'TEST_TICKET_ID=%s\n' "$(shell_quote "$TEST_TICKET_ID")"
        printf 'TEST_TICKET_NUMBER=%s\n' "$(shell_quote "$TEST_TICKET_NUMBER")"
        printf '\n'
        printf 'TEST_QUEUE_ID=%s\n' "$(shell_quote "$TEST_QUEUE_ID")"
        printf 'TEST_QUEUE_DISPLAY_NAME=%s\n' "$(shell_quote "$TEST_QUEUE_DISPLAY_NAME")"
        printf 'TEST_QUEUE_NAME_PATH=%s\n' "$(shell_quote "$TEST_QUEUE_NAME_PATH")"
        printf 'TEST_PRIORITY_NAME=%s\n' "$(shell_quote "$TEST_PRIORITY_NAME")"
        printf '\n'
        printf 'TEST_CUSTOMER_SEARCH=%s\n' "$(shell_quote "$TEST_CUSTOMER_SEARCH")"
        printf 'TEST_CUSTOMER_LOGIN=%s\n' "$(shell_quote "$TEST_CUSTOMER_LOGIN")"
        printf '\n'
        printf 'TEST_HOSTNAME=%s\n' "$(shell_quote "$TEST_HOSTNAME")"
        printf '\n'
        printf 'RUN_WRITE_TESTS=%s\n' "$(shell_quote "$RUN_WRITE_TESTS")"
        printf 'LOG_DIR=%s\n' "$(shell_quote "$LOG_DIR")"
    } >"$TEST_ENV_FILE"
    chmod 600 "$TEST_ENV_FILE"
}

collect_config() {
    local first_run=no
    if [ ! -f "$TEST_ENV_FILE" ]; then
        first_run=yes
    fi

    load_env_file

    prompt_required ZNUNY_BASE_URL 'Znuny base URL'
    ZNUNY_BASE_URL=$(trim_slash "$ZNUNY_BASE_URL")

    prompt_required ZNUNY_API_USER 'API user'
    if [ -z "${EXPECTED_VERSION:-}" ] && [ -z "${MIN_EXPECTED_VERSION:-}" ]; then
        prompt_required MIN_EXPECTED_VERSION 'Minimum expected package version'
    fi
    prompt_optional EXPECTED_VERSION 'Optional exact expected package version'
    prompt_required TEST_TICKET_ID 'Test ticket ID'
    prompt_required TEST_TICKET_NUMBER 'Test ticket number'
    prompt_required TEST_QUEUE_ID 'Test queue ID'
    prompt_required TEST_QUEUE_DISPLAY_NAME 'Test queue display name'
    prompt_optional TEST_QUEUE_NAME_PATH 'Test queue path name'
    if [ -z "${TEST_QUEUE_NAME_PATH:-}" ] && [ -n "${TEST_QUEUE_DISPLAY_NAME:-}" ]; then
        TEST_QUEUE_NAME_PATH=$(urlencode_spaces_only "$TEST_QUEUE_DISPLAY_NAME")
    fi
    prompt_required TEST_QUEUE_NAME_PATH 'Test queue path name'
    prompt_required TEST_PRIORITY_NAME 'Test priority name'
    prompt_required TEST_CUSTOMER_SEARCH 'Customer search string'
    prompt_required TEST_CUSTOMER_LOGIN 'Customer login'
    prompt_required TEST_HOSTNAME 'Test hostname'
    prompt_yes_no_default_no RUN_WRITE_TESTS 'Run write tests by default?'
    prompt_required LOG_DIR 'Log directory'
    prompt_password_if_needed

    case "$RUN_WRITE_TESTS" in
        y|Y|yes|YES|Yes|true|TRUE|1) RUN_WRITE_TESTS=yes ;;
        *) RUN_WRITE_TESTS=no ;;
    esac

    if [ "$first_run" = "yes" ]; then
        local store_password=no
        printf 'Store API password in env file? [y/N]: '
        IFS= read -r store_password
        case "$store_password" in
            y|Y|yes|YES|Yes) store_password=yes ;;
            *) store_password=no ;;
        esac
        write_env_file "$store_password"
        printf 'Created %s with permissions 600.\n' "$TEST_ENV_FILE"
    fi
}

init_log() {
    mkdir -p "$LOG_DIR"
    LOG_FILE="$LOG_DIR/advanced-znuny-agentlist-smoke-$(date +%Y%m%d-%H%M%S).log"
    : >"$LOG_FILE"
    chmod 600 "$LOG_FILE" 2>/dev/null || true
    log_line "AdvancedZnunyAgentListREST smoke test"
    log_line "Log file: $LOG_FILE"
    log_line "Base URL: $ZNUNY_BASE_URL"
    log_line "API user: $ZNUNY_API_USER"
    log_line "API password: [hidden]"
}

json_escape() {
    local value=${1-}
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//$'\n'/\\n}
    value=${value//$'\r'/\\r}
    value=${value//$'\t'/\\t}
    printf '%s' "$value"
}

urlencode() {
    local string=${1-}
    local length=${#string}
    local i char out=""
    local LC_ALL=C
    for (( i = 0; i < length; i++ )); do
        char=${string:i:1}
        case "$char" in
            [a-zA-Z0-9.~_-]) out+="$char" ;;
            *) printf -v out '%s%%%02X' "$out" "'$char" ;;
        esac
    done
    printf '%s' "$out"
}

auth_query() {
    printf 'UserLogin=%s&Password=%s' "$(urlencode "$ZNUNY_API_USER")" "$(urlencode "$ZNUNY_API_PASS")"
}

append_query() {
    local path=$1
    local query=$2
    if [[ "$path" == *\?* ]]; then
        printf '%s&%s' "$path" "$query"
    else
        printf '%s?%s' "$path" "$query"
    fi
}

pretty_json() {
    local body=$1
    if command -v jq >/dev/null 2>&1; then
        printf '%s' "$body" | jq . 2>/dev/null || printf '%s\n' "$body"
    else
        printf '%s\n' "$body"
    fi
}

json_string() {
    local body=$1
    local key=$2
    if command -v jq >/dev/null 2>&1; then
        printf '%s' "$body" | jq -r --arg key "$key" '.. | objects | select(has($key)) | .[$key] | strings' 2>/dev/null | head -n 1
    else
        printf '%s' "$body" | sed -n "s/.*\"$key\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p" | head -n 1
    fi
}

version_ge() {
    local actual=$1
    local minimum=$2
    local a_major a_minor a_patch m_major m_minor m_patch
    IFS=. read -r a_major a_minor a_patch <<EOF
$actual
EOF
    IFS=. read -r m_major m_minor m_patch <<EOF
$minimum
EOF
    a_major=${a_major:-0}; a_minor=${a_minor:-0}; a_patch=${a_patch:-0}
    m_major=${m_major:-0}; m_minor=${m_minor:-0}; m_patch=${m_patch:-0}

    if [ "$a_major" -gt "$m_major" ]; then return 0; fi
    if [ "$a_major" -lt "$m_major" ]; then return 1; fi
    if [ "$a_minor" -gt "$m_minor" ]; then return 0; fi
    if [ "$a_minor" -lt "$m_minor" ]; then return 1; fi
    [ "$a_patch" -ge "$m_patch" ]
}

LAST_STATUS=""
LAST_BODY=""

request() {
    local method=$1
    local path=$2
    local expected_status=${3:-200}
    local body=${4:-}
    local use_auth=${5:-yes}
    local allow_error=${6:-no}

    local request_path=$path
    if [ "$use_auth" = "yes" ]; then
        request_path=$(append_query "$request_path" "$(auth_query)")
    fi

    local url="$ZNUNY_BASE_URL$request_path"
    local body_file status response
    body_file=$(mktemp)

    log_line ""
    log_line "$method $(mask_text "$request_path")"
    if [ -n "$body" ]; then
        if [ "$path" = "/Session" ]; then
            log_line "Request body: {\"UserLogin\":\"$ZNUNY_API_USER\",\"Password\":\"[hidden]\"}"
        else
            log_line "Request body: $(mask_text "$body")"
        fi
    fi

    if [ "$method" = "GET" ]; then
        status=$(curl -sS -o "$body_file" -w '%{http_code}' "$url" || true)
    else
        status=$(curl -sS -o "$body_file" -w '%{http_code}' -X "$method" -H 'Content-Type: application/json' --data "$body" "$url" || true)
    fi

    response=$(cat "$body_file")
    rm -f "$body_file"

    LAST_STATUS=$status
    LAST_BODY=$response

    log_line "HTTP status: $status"
    log_line "Response:"
    pretty_json "$(mask_text "$response")" | while IFS= read -r line; do log_line "$line"; done

    if [ "$status" != "$expected_status" ]; then
        fail "$method $path returned HTTP $status, expected $expected_status."
        return
    fi

    if [ "$allow_error" != "yes" ]; then
        if printf '%s' "$response" | grep -q '"ErrorCode"'; then
            fail "$method $path returned ErrorCode."
            return
        fi
        if printf '%s' "$response" | grep -q 'ZnunyAgentList.AuthFail'; then
            fail "$method $path returned ZnunyAgentList.AuthFail."
            return
        fi
    fi

    pass "$method $path returned expected HTTP $expected_status."
}

expect_body_contains() {
    local marker=$1
    local description=$2
    if printf '%s' "$LAST_BODY" | grep -Fq "$marker"; then
        pass "$description"
    else
        fail "$description"
    fi
}

expect_body_not_contains() {
    local marker=$1
    local description=$2
    if printf '%s' "$LAST_BODY" | grep -Fq "$marker"; then
        fail "$description"
    else
        pass "$description"
    fi
}

expect_body_regex() {
    local pattern=$1
    local description=$2
    if printf '%s' "$LAST_BODY" | grep -Eq "$pattern"; then
        pass "$description"
    else
        fail "$description"
    fi
}

expect_body_not_regex() {
    local pattern=$1
    local description=$2
    if printf '%s' "$LAST_BODY" | grep -Eq "$pattern"; then
        fail "$description"
    else
        pass "$description"
    fi
}

test_health() {
    section 'Core package endpoints'
    request GET /Health 200 "" yes no
    local actual_version
    actual_version=$(json_string "$LAST_BODY" Version)
    if [ -z "$actual_version" ]; then
        fail 'Health response contains Version.'
    elif [ -n "${EXPECTED_VERSION:-}" ]; then
        if [ "$actual_version" = "$EXPECTED_VERSION" ]; then
            pass "Health version exactly matches $EXPECTED_VERSION."
        else
            fail "Health version $actual_version does not match expected $EXPECTED_VERSION."
        fi
    else
        if version_ge "$actual_version" "$MIN_EXPECTED_VERSION"; then
            pass "Health version $actual_version is >= $MIN_EXPECTED_VERSION."
        else
            fail "Health version $actual_version is lower than $MIN_EXPECTED_VERSION."
        fi
    fi

    request GET /SystemConfig 200 "" yes no
}

test_session() {
    section 'Session compatibility'
    local body session_id
    body="{\"UserLogin\":\"$(json_escape "$ZNUNY_API_USER")\",\"Password\":\"$(json_escape "$ZNUNY_API_PASS")\"}"
    request POST /Session 200 "$body" no no
    session_id=$(json_string "$LAST_BODY" SessionID)
    if [ -n "$session_id" ]; then
        pass 'SessionCreate returned SessionID.'
        request GET "/Session?SessionID=$(urlencode "$session_id")" 200 "" no no
        request GET "/Session/$(urlencode "$session_id")" 200 "" no no
    else
        warn 'SessionCreate did not return a parseable SessionID; SessionGet checks skipped.'
        skip 'GET /Session?SessionID=... skipped.'
        skip 'GET /Session/:SessionID skipped.'
    fi
}

test_agents_queues() {
    section 'Agents and queues'
    request GET /Agent 200 "" yes no
    request GET /Queue 200 "" yes no
    request GET "/Queue/$(urlencode "$TEST_QUEUE_ID")" 200 "" yes no
    request GET "/QueueByName/$TEST_QUEUE_NAME_PATH" 200 "" yes no
}

test_customer_users() {
    section 'Customer users'
    request GET "/CustomerUser?Search=$(urlencode "$TEST_CUSTOMER_SEARCH")&Limit=10" 200 "" yes no
    request GET "/CustomerUser/$(urlencode "$TEST_CUSTOMER_LOGIN")" 200 "" yes no
    expect_body_contains "$TEST_CUSTOMER_LOGIN" 'CustomerUser::Get response contains configured customer login.'
}

test_dictionaries() {
    section 'Ticket dictionaries'
    request GET /TicketState 200 "" yes no
    request GET /TicketPriority 200 "" yes no
    if printf '%s' "$LAST_BODY" | grep -Fq 'TicketPriorities'; then
        pass 'TicketPriority response contains TicketPriorities.'
    elif [ -n "${TEST_PRIORITY_NAME:-}" ] && printf '%s' "$LAST_BODY" | grep -Fq "$TEST_PRIORITY_NAME"; then
        pass 'TicketPriority response contains configured priority name.'
    elif [ -n "${TEST_PRIORITY_MARKER:-}" ] && printf '%s' "$LAST_BODY" | grep -Fq "$TEST_PRIORITY_MARKER"; then
        pass 'TicketPriority response contains configured priority marker.'
    else
        fail 'TicketPriority response contains TicketPriorities, configured priority name, or configured priority marker.'
    fi
    request GET /TicketType 200 "" yes no
    request GET /Service 200 "" yes no
    request GET /SLA 200 "" yes no
}

test_defaults_validation() {
    section 'Defaults and validation'
    request GET "/ResolveTicketDefaults?Hostname=$(urlencode "$TEST_HOSTNAME")" 200 "" yes no
    expect_body_contains "$TEST_HOSTNAME" 'ResolveTicketDefaults Hostname response contains configured hostname.'
    expect_body_not_regex '"HostName"[[:space:]]*:[[:space:]]*"255"' 'ResolveTicketDefaults does not return HostName 255.'
    expect_body_not_regex '"QueueName"[[:space:]]*:[[:space:]]*"255"' 'ResolveTicketDefaults does not return QueueName 255.'
    expect_body_not_regex '"CustomerUserLogin"[[:space:]]*:[[:space:]]*"255Clients"' 'ResolveTicketDefaults does not return CustomerUserLogin 255Clients.'

    request GET "/ResolveTicketDefaults?HostName=$(urlencode "$TEST_HOSTNAME")" 200 "" yes no
    expect_body_contains "$TEST_HOSTNAME" 'ResolveTicketDefaults HostName response contains configured hostname.'
    expect_body_not_regex '"HostName"[[:space:]]*:[[:space:]]*"255"' 'ResolveTicketDefaults alternate HostName does not return HostName 255.'
    expect_body_not_regex '"QueueName"[[:space:]]*:[[:space:]]*"255"' 'ResolveTicketDefaults alternate HostName does not return QueueName 255.'
    expect_body_not_regex '"CustomerUserLogin"[[:space:]]*:[[:space:]]*"255Clients"' 'ResolveTicketDefaults alternate HostName does not return CustomerUserLogin 255Clients.'

    local validate_body
    validate_body="{\"Queue\":\"$(json_escape "$TEST_QUEUE_DISPLAY_NAME")\",\"CustomerUser\":\"$(json_escape "$TEST_CUSTOMER_LOGIN")\",\"Title\":\"ZnunyAgentList smoke validation\",\"State\":\"new\",\"Priority\":\"$(json_escape "$TEST_PRIORITY_NAME")\""
    if [ -n "${TEST_OWNER_ID:-}" ]; then
        validate_body="$validate_body,\"OwnerID\":\"$(json_escape "$TEST_OWNER_ID")\""
    fi
    validate_body="$validate_body}"

    request POST /ValidateTicketCreate 200 "$validate_body" yes no
}

test_safe_tickets() {
    section 'Safe ticket get/search'
    request GET "/ZnunyAgentListTicket/$(urlencode "$TEST_TICKET_ID")" 200 "" yes no
    expect_body_contains "$TEST_TICKET_ID" 'Safe ticket get by ID contains configured ticket ID.'

    request GET "/ZnunyAgentListTicketNumber/$(urlencode "$TEST_TICKET_NUMBER")" 200 "" yes no
    expect_body_contains "$TEST_TICKET_NUMBER" 'Safe ticket get by number contains configured ticket number.'

    request GET /ZnunyAgentListTicketSearch 200 "" yes no
    expect_body_contains 'At least one search filter is required.' 'Safe ticket search no-filter warning is present.'

    request GET "/ZnunyAgentListTicketSearch?TicketNumber=$(urlencode "$TEST_TICKET_NUMBER")" 200 "" yes no
    expect_body_contains "$TEST_TICKET_NUMBER" 'Safe ticket search by TicketNumber contains configured ticket number.'

    request GET "/ZnunyAgentListTicketSearch?Queue=$(urlencode "$TEST_QUEUE_DISPLAY_NAME")&StateType=open&Limit=5" 200 "" yes no
}

test_generic_ticket_connector() {
    section 'GenericTicketConnector compatibility routes'
    request GET "/Ticket?TicketNumber=$(urlencode "$TEST_TICKET_NUMBER")" 200 "" yes no
    request GET "/Ticket/$(urlencode "$TEST_TICKET_ID")" 200 "" yes no
    request GET "/TicketHistory/$(urlencode "$TEST_TICKET_ID")" 200 "" yes no
    request GET "/TicketList?TicketID=$(urlencode "$TEST_TICKET_ID")" 200 "" yes no
}

test_write_lifecycle() {
    section 'Optional controlled write lifecycle'
    if [ "$RUN_WRITE_TESTS" != "yes" ]; then
        skip 'Write lifecycle tests skipped because RUN_WRITE_TESTS is not yes.'
        return
    fi

    warn 'RUN_WRITE_TESTS=yes: this section performs real ticket writes.'

    local article_body close_body reopen_body
    article_body="{\"TicketID\":\"$(json_escape "$TEST_TICKET_ID")\",\"Kind\":\"internal_note\",\"Subject\":\"ZnunyAgentList smoke test article\",\"Body\":\"Repository smoke test internal note.\"}"
    close_body="{\"TicketID\":\"$(json_escape "$TEST_TICKET_ID")\",\"Kind\":\"internal_note\",\"Subject\":\"ZnunyAgentList smoke test close\",\"Body\":\"Repository smoke test closing ticket.\",\"Reason\":\"ZnunyAgentList smoke test close\"}"
    reopen_body="{\"TicketID\":\"$(json_escape "$TEST_TICKET_ID")\",\"Kind\":\"internal_note\",\"Subject\":\"ZnunyAgentList smoke test reopen\",\"Body\":\"Repository smoke test reopening ticket.\",\"Reason\":\"ZnunyAgentList smoke test reopen\"}"

    request POST /TicketArticle 200 "$article_body" yes no
    request POST /TicketClose 200 "$close_body" yes no
    request GET "/ZnunyAgentListTicket/$(urlencode "$TEST_TICKET_ID")" 200 "" yes no
    expect_body_regex '"StateType"[[:space:]]*:[[:space:]]*"closed"' 'Ticket is closed after TicketClose.'
    request POST /TicketReopen 200 "$reopen_body" yes no
    request GET "/ZnunyAgentListTicket/$(urlencode "$TEST_TICKET_ID")" 200 "" yes no
    expect_body_regex '"StateType"[[:space:]]*:[[:space:]]*"open"' 'Ticket is open after TicketReopen.'
}

main() {
    collect_config
    init_log

    test_health
    test_session
    test_agents_queues
    test_customer_users
    test_dictionaries
    test_defaults_validation
    test_safe_tickets
    test_generic_ticket_connector
    test_write_lifecycle

    section 'Summary'
    log_line "PASS: $PASS"
    log_line "WARN: $WARN"
    log_line "FAIL: $FAIL"
    log_line "SKIP: $SKIP"

    if [ "$FAIL" -eq 0 ]; then
        log_line 'RESULT: OK'
        exit 0
    fi

    log_line 'RESULT: FAILED'
    exit 1
}

main "$@"

# First run, interactive setup:
# bash scripts/test-advanced-znuny-agentlist-all.sh
#
# Next runs use:
# scripts/test-advanced-znuny-agentlist-all.env
#
# With password supplied through environment:
# ZNUNY_API_PASS='SECRET' bash scripts/test-advanced-znuny-agentlist-all.sh
#
# Force write lifecycle for this run:
# RUN_WRITE_TESTS=yes bash scripts/test-advanced-znuny-agentlist-all.sh
